# Generated by Django 4.2.1 on 2023-06-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
